### ISSUE TITLE
Usage in the README is outdated

### ISSUE THREAD

**Issue by PaulRBerg** [rhlsthrm/buidler-typechain#1]
Hey! Thanks for creating this plugin. I tried to follow the instructions in the README:

```ts
const provider = ethers.provider;
let [wallet] = getWallets(provider);
```

But these don't work anymore as of @nomiclabs/buidler@1.3.3 and ethereum-waffle@2.5.0:

<img width="906" alt="Capture d’écran 2020-05-20 à 15 24 43" src="https://user-images.githubusercontent.com/8782666/82445844-3147d680-9aae-11ea-9dff-8b62051d42df.png">

Related: https://github.com/EthWorks/Waffle/issues/270

**Comment by PaulRBerg** [comment]
I think I figured it out, as per @pcowgill's work on chicago-ethereum/quadratic-funding:

https://github.com/chicago-ethereum/quadratic-funding/blob/master/contract-project/test/cemToken.ts

One ought to now use the waffle's provider and pull the wallets from there, not ethers:

```ts
import { deployContract } from "ethereum-waffle";
import { waffle } from "@nomiclabs/buidler";

...

const provider = waffle.provider;
let [wallet] = provider.getWallets();
let greeter = (await deployContract(alice, GreeterArtifact)) as Greeter;
```

**Comment by rhlsthrm** [comment]
Thanks for the input! Everything is updated now.
